destination: _site

name: "Yannis Jaquet"
description: "The small personal page of Yannis Jaquet"
url: "yannis.github.io"

paginate: 10

markdown: rdiscount
permalink: pretty
pygments: true
encoding: UTF-8
exclude: ['vendor']
