destination: _site

name: "Yannis Jaquet"
description: "The small personal page of Yannis Jaquet"
url: "yannis.github.io"

paginate: 10

permalink: pretty
highlighter: pygments
encoding: UTF-8
exclude: ['vendor']
sass:
  style: compressed
